version: 2
jobs:
  job-one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10
        
  job-two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello from build 2"
      - run: sleep 15
        
workflows:
  version: 2
  one_and_two:
    jobs:
      - job-one # Name of the first job
      - job-two # Name of the second job
