version: 2
jobs:
  job-one:
    build:
      docker:
        - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "A first hello"
        
  job-two:
    build:
      docker:
        - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "Hello from build 2"
        
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
